// Buscar usuário no banco de dados por email
GET http://localhost:8080/getUserByEmail/brunok@gmail.com
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va0BnbWFpbC5jb20iLCJleHAiOjE2ODcwNDI2MDcsImlkIjoiNjQ4Y2U4OWE3NGFhYmQ1YmI0MzI0ZTcwIiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.V-dqPgu06-PaF3wMBiZNxKWePy_J3U5NeCTTfEbf-2I

###

// Buscar usuário no banco de dados pelo ID
GET http://localhost:8080/getUserById/648b5fc42cc5eaefc4efae38
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5vMTIxMkBnbWFpbC5jb20iLCJleHAiOjE2ODY5NDIwNjQsImlkIjoiNjQ4YjVmYzQyY2M1ZWFlZmM0ZWZhZTM4IiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.YO9pi6UxKl_RUVWFyUnwKXCAfG3ZPpY3v98bbwNgSlA
###

// Criar um usuario dentro do banco de dados
POST http://localhost:8080/createUser
Content-Type: application/json

{
  "email": "brunokkk@gmail.com",
  "age": 23,
  "password": "bruno#!@!dwdw",
  "name": "Bruno Correia",
  "nickname": "brunin",
  "nationality": "Brazil"
}
###

POST http://localhost:8080/createBet
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va2trQGdtYWlsLmNvbSIsImV4cCI6MTY4NzA1NTY2NywiaWQiOiI2NDhkMWJhYTdiYTcwYzJhNGFmMDM4Y2UiLCJuYW1lIjoiQnJ1bm8gQ29ycmVpYSIsIm5hdGlvbmFsaXR5IjoiQnJhemlsIiwibmlja25hbWUiOiJicnVuaW4ifQ.IzLdq1aWuOTxr2XqdV0LogZ7KCTdOGMLleFqx7ra1ho


{
  "nickname": "brunin",
  "date": "06/16/2023",
  "bookmaker": "Bet365",
  "sport": "CS:GO",
  "description": "Oddik ML vs Seleça do BT",
  "odd": 1.725,
  "investment": 65,
  "tipster": "Telegram",
  "winner": true
}

###

// Atualiza um usuario já criado dentro do banco de dados
PUT http://localhost:8080/updateUser/648b63613592346a986f11d0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va0BnbWFpbC5jb20iLCJleHAiOjE2ODY5NDI5NTQsImlkIjoiNjQ4YjYzNjEzNTkyMzQ2YTk4NmYxMWQwIiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.ldrxsUIxCSzpAjob8j4ERBV4czyGJepPHGx-UFMljG0

{
  "age": 24,
  "nationality": "Portugal"
}
###

// Apaga um usuário do banco de dados dado um userId
DELETE http://localhost:8080/deleteUser/648ce89a74aabd5bb4324e70
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va2tAZ21haWwuY29tIiwiZXhwIjoxNjg3MDQ2NDk4LCJpZCI6IjY0OGNmNzZhMWEwNzQxZTZiMGQ5YjY0NiIsIm5hbWUiOiJCcnVubyBDb3JyZWlhIiwibmF0aW9uYWxpdHkiOiJCcmF6aWwiLCJuaWNrbmFtZSI6ImJydW5pbiJ9.E8vfw1aj18clfu_FF2awpmhrEQW9od0wCxfppATN7xw

###

// Realiza o login do usuário com email e senha
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "brunokkk@gmail.com",
    "password": "bruno#!@!dwdw"
}

###
