// Buscar usuário no banco de dados por email
GET http://localhost:8080/getUserByEmail/brunok@gmail.com
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va0BnbWFpbC5jb20iLCJleHAiOjE2ODY5NDI5NTQsImlkIjoiNjQ4YjYzNjEzNTkyMzQ2YTk4NmYxMWQwIiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.ldrxsUIxCSzpAjob8j4ERBV4czyGJepPHGx-UFMljG0
###

// Buscar usuário no banco de dados pelo ID
GET http://localhost:8080/getUserById/648b5fc42cc5eaefc4efae38
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5vMTIxMkBnbWFpbC5jb20iLCJleHAiOjE2ODY5NDIwNjQsImlkIjoiNjQ4YjVmYzQyY2M1ZWFlZmM0ZWZhZTM4IiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.YO9pi6UxKl_RUVWFyUnwKXCAfG3ZPpY3v98bbwNgSlA
###

// Criar um usuario dentro do banco de dados
POST http://localhost:8080/createUser
Content-Type: application/json

{
  "email": "brunok@gmail.com",
  "age": 23,
  "password": "bruno#!@!dwdw",
  "name": "Bruno Correia",
  "nationality": "Brazil"
}
###

// Atualiza um usuario já criado dentro do banco de dados
PUT http://localhost:8080/updateUser/648b63613592346a986f11d0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6ImJydW5va0BnbWFpbC5jb20iLCJleHAiOjE2ODY5NDI5NTQsImlkIjoiNjQ4YjYzNjEzNTkyMzQ2YTk4NmYxMWQwIiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IkJyYXppbCJ9.ldrxsUIxCSzpAjob8j4ERBV4czyGJepPHGx-UFMljG0

{
  "age": 24,
  "nationality": "Portugal"
}
###

// Apaga um usuário do banco de dados dado um userId
DELETE http://localhost:8080/deleteUser/648b5fc42cc5eaefc4efae38
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjI0LCJlbWFpbCI6ImJydW5va0BnbWFpbC5jb20iLCJleHAiOjE2ODY5NDMxMzYsImlkIjoiNjQ4YjYzNjEzNTkyMzQ2YTk4NmYxMWQwIiwibmFtZSI6IkJydW5vIENvcnJlaWEiLCJuYXRpb25hbGl0eSI6IlBvcnR1Z2FsIn0.f6GXvnqiO6YDWwUbaCXDwWwC5sz2nFSvxDg8zu-p86o
###

// Realiza o login do usuário com email e senha
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "brunok@gmail.com",
    "password": "bruno#!@!dwdw"
}
###
